use std::fmt;
use serde::Serialize;

#[derive(thiserror::Error, Debug)]
pub enum AreaParseError {
    #[error("unknown postcode area: {0}")]
    UnknownPostCodeArea(String),
}

#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize)]
pub enum PostCodeArea {
    Aberdeen,
    StAlbans,
    Birmingham,
    Bath,
    Blackburn,
    Bradford,
    Bournemouth,
    Bolton,
    Brighton,
    Bromley,
    Bristol,
    Belfast,
    Carlisle,
    Cambridge,
    Cardiff,
    Chester,
    Chelmsford,
    Colchester,
    Croydon,
    Canterbury,
    Coventry,
    Crewe,
    Dartford,
    Dundee,
    Derby,
    Dumfries,
    Durham,
    Darlington,
    Doncaster,
    Dorchester,
    Dudley,
    LondonE,
    LondonEC,
    Edinburgh,
    Enfield,
    Exeter,
    Falkirk,
    Blackpool,
    Glasgow,
    Gloucester,
    Guildford,
    Guernsey,
    Harrow,
    Huddersfield,
    Harrogate,
    HemelHempstead,
    Hereford,
    ComhairleNanEileanSiar,
    Hull,
    Halifax,
    Ilford,
    IsleOfMan,
    Ipswich,
    Inverness,
    Jersey,
    Kilmarnock,
    Kingston,
    Kirkwall,
    Kirkcaldy,
    Liverpool,
    Lancaster,
    Llandrindod,
    Leicester,
    Llandudno,
    Lincoln,
    Leeds,
    Luton,
    Manchester,
    Medway,
    MiltonKeynes,
    Motherwell,
    LondonN,
    Newcastle,
    Nottingham,
    Northampton,
    Newport,
    Norwich,
    LondonNW,
    Oldham,
    Oxford,
    Paisley,
    Peterborough,
    Perth,
    Plymouth,
    Portsmouth,
    Preston,
    AwardingBodies,
    Reading,
    Redhill,
    Romford,
    Sheffield,
    Swansea,
    LondonSE,
    Stevenage,
    Stockport,
    Slough,
    Sutton,
    Swindon,
    Southampton,
    Salisbury,
    Sunderland,
    Southend,
    StokeOnTrent,
    LondonSW,
    Shrewsbury,
    Taunton,
    Galashiels,
    Telford,
    Tonbridge,
    Torquay,
    Truro,
    Cleveland,
    Twickenham,
    Southall,
    LondonW,
    Warrington,
    LondonWC,
    Watford,
    Wakefield,
    Wigan,
    Worcester,
    Walsall,
    Wolverhampton,
    York,
    Shetland,
}

impl fmt::Display for PostCodeArea {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl PostCodeArea {
    pub fn new(s: &str) -> Result<Self, AreaParseError> {
        match s.to_uppercase().as_str() {
            "AB" => Ok(PostCodeArea::Aberdeen),
            "AL" => Ok(PostCodeArea::StAlbans),
            "B" => Ok(PostCodeArea::Birmingham),
            "BA" => Ok(PostCodeArea::Bath),
            "BB" => Ok(PostCodeArea::Blackburn),
            "BD" => Ok(PostCodeArea::Bradford),
            "BH" => Ok(PostCodeArea::Bournemouth),
            "BL" => Ok(PostCodeArea::Bolton),
            "BN" => Ok(PostCodeArea::Brighton),
            "BR" => Ok(PostCodeArea::Bromley),
            "BS" => Ok(PostCodeArea::Bristol),
            "BT" => Ok(PostCodeArea::Belfast),
            "CA" => Ok(PostCodeArea::Carlisle),
            "CB" => Ok(PostCodeArea::Cambridge),
            "CF" => Ok(PostCodeArea::Cardiff),
            "CH" => Ok(PostCodeArea::Chester),
            "CM" => Ok(PostCodeArea::Chelmsford),
            "CO" => Ok(PostCodeArea::Colchester),
            "CR" => Ok(PostCodeArea::Croydon),
            "CT" => Ok(PostCodeArea::Canterbury),
            "CV" => Ok(PostCodeArea::Coventry),
            "CW" => Ok(PostCodeArea::Crewe),
            "DA" => Ok(PostCodeArea::Dartford),
            "DD" => Ok(PostCodeArea::Dundee),
            "DE" => Ok(PostCodeArea::Derby),
            "DG" => Ok(PostCodeArea::Dumfries),
            "DH" => Ok(PostCodeArea::Durham),
            "DL" => Ok(PostCodeArea::Darlington),
            "DN" => Ok(PostCodeArea::Doncaster),
            "DT" => Ok(PostCodeArea::Dorchester),
            "DY" => Ok(PostCodeArea::Dudley),
            "E" => Ok(PostCodeArea::LondonE),
            "EC" => Ok(PostCodeArea::LondonEC),
            "EH" => Ok(PostCodeArea::Edinburgh),
            "EN" => Ok(PostCodeArea::Enfield),
            "EX" => Ok(PostCodeArea::Exeter),
            "FK" => Ok(PostCodeArea::Falkirk),
            "FY" => Ok(PostCodeArea::Blackpool),
            "G" => Ok(PostCodeArea::Glasgow),
            "GL" => Ok(PostCodeArea::Gloucester),
            "GU" => Ok(PostCodeArea::Guildford),
            "GY" => Ok(PostCodeArea::Guernsey),
            "HA" => Ok(PostCodeArea::Harrow),
            "HD" => Ok(PostCodeArea::Huddersfield),
            "HG" => Ok(PostCodeArea::Harrogate),
            "HP" => Ok(PostCodeArea::HemelHempstead),
            "HR" => Ok(PostCodeArea::Hereford),
            "HS" => Ok(PostCodeArea::ComhairleNanEileanSiar),
            "HU" => Ok(PostCodeArea::Hull),
            "HX" => Ok(PostCodeArea::Halifax),
            "IG" => Ok(PostCodeArea::Ilford),
            "IM" => Ok(PostCodeArea::IsleOfMan),
            "IP" => Ok(PostCodeArea::Ipswich),
            "IV" => Ok(PostCodeArea::Inverness),
            "JE" => Ok(PostCodeArea::Jersey),
            "KA" => Ok(PostCodeArea::Kilmarnock),
            "KT" => Ok(PostCodeArea::Kingston),
            "KW" => Ok(PostCodeArea::Kirkwall),
            "KY" => Ok(PostCodeArea::Kirkcaldy),
            "L" => Ok(PostCodeArea::Liverpool),
            "LA" => Ok(PostCodeArea::Lancaster),
            "LD" => Ok(PostCodeArea::Llandrindod),
            "LE" => Ok(PostCodeArea::Leicester),
            "LL" => Ok(PostCodeArea::Llandudno),
            "LN" => Ok(PostCodeArea::Lincoln),
            "LS" => Ok(PostCodeArea::Leeds),
            "LU" => Ok(PostCodeArea::Luton),
            "M" => Ok(PostCodeArea::Manchester),
            "ME" => Ok(PostCodeArea::Medway),
            "MK" => Ok(PostCodeArea::MiltonKeynes),
            "ML" => Ok(PostCodeArea::Motherwell),
            "N" => Ok(PostCodeArea::LondonN),
            "NE" => Ok(PostCodeArea::Newcastle),
            "NG" => Ok(PostCodeArea::Nottingham),
            "NN" => Ok(PostCodeArea::Northampton),
            "NP" => Ok(PostCodeArea::Newport),
            "NR" => Ok(PostCodeArea::Norwich),
            "NW" => Ok(PostCodeArea::LondonNW),
            "OL" => Ok(PostCodeArea::Oldham),
            "OX" => Ok(PostCodeArea::Oxford),
            "PA" => Ok(PostCodeArea::Paisley),
            "PE" => Ok(PostCodeArea::Peterborough),
            "PH" => Ok(PostCodeArea::Perth),
            "PL" => Ok(PostCodeArea::Plymouth),
            "PO" => Ok(PostCodeArea::Portsmouth),
            "PR" => Ok(PostCodeArea::Preston),
            "QC" => Ok(PostCodeArea::AwardingBodies),
            "RG" => Ok(PostCodeArea::Reading),
            "RH" => Ok(PostCodeArea::Redhill),
            "RM" => Ok(PostCodeArea::Romford),
            "S" => Ok(PostCodeArea::Sheffield),
            "SA" => Ok(PostCodeArea::Swansea),
            "SE" => Ok(PostCodeArea::LondonSE),
            "SG" => Ok(PostCodeArea::Stevenage),
            "SK" => Ok(PostCodeArea::Stockport),
            "SL" => Ok(PostCodeArea::Slough),
            "SM" => Ok(PostCodeArea::Sutton),
            "SN" => Ok(PostCodeArea::Swindon),
            "SO" => Ok(PostCodeArea::Southampton),
            "SP" => Ok(PostCodeArea::Salisbury),
            "SR" => Ok(PostCodeArea::Sunderland),
            "SS" => Ok(PostCodeArea::Southend),
            "ST" => Ok(PostCodeArea::StokeOnTrent),
            "SW" => Ok(PostCodeArea::LondonSW),
            "SY" => Ok(PostCodeArea::Shrewsbury),
            "TA" => Ok(PostCodeArea::Taunton),
            "TD" => Ok(PostCodeArea::Galashiels),
            "TF" => Ok(PostCodeArea::Telford),
            "TN" => Ok(PostCodeArea::Tonbridge),
            "TQ" => Ok(PostCodeArea::Torquay),
            "TR" => Ok(PostCodeArea::Truro),
            "TS" => Ok(PostCodeArea::Cleveland),
            "TW" => Ok(PostCodeArea::Twickenham),
            "UB" => Ok(PostCodeArea::Southall),
            "W" => Ok(PostCodeArea::LondonW),
            "WA" => Ok(PostCodeArea::Warrington),
            "WC" => Ok(PostCodeArea::LondonWC),
            "WD" => Ok(PostCodeArea::Watford),
            "WF" => Ok(PostCodeArea::Wakefield),
            "WN" => Ok(PostCodeArea::Wigan),
            "WR" => Ok(PostCodeArea::Worcester),
            "WS" => Ok(PostCodeArea::Walsall),
            "WV" => Ok(PostCodeArea::Wolverhampton),
            "YO" => Ok(PostCodeArea::York),
            "ZE" => Ok(PostCodeArea::Shetland),
            _ => Err(AreaParseError::UnknownPostCodeArea(s.to_string())),
        }
    }

    pub fn as_str(&self) -> &str {
        match self {
            PostCodeArea::Aberdeen => "AB",
            PostCodeArea::StAlbans => "AL",
            PostCodeArea::Birmingham => "B",
            PostCodeArea::Bath => "BA",
            PostCodeArea::Blackburn => "BB",
            PostCodeArea::Bradford => "BD",
            PostCodeArea::Bournemouth => "BH",
            PostCodeArea::Bolton => "BL",
            PostCodeArea::Brighton => "BN",
            PostCodeArea::Bromley => "BR",
            PostCodeArea::Bristol => "BS",
            PostCodeArea::Belfast => "BT",
            PostCodeArea::Carlisle => "CA",
            PostCodeArea::Cambridge => "CB",
            PostCodeArea::Cardiff => "CF",
            PostCodeArea::Chester => "CH",
            PostCodeArea::Chelmsford => "CM",
            PostCodeArea::Colchester => "CO",
            PostCodeArea::Croydon => "CR",
            PostCodeArea::Canterbury => "CT",
            PostCodeArea::Coventry => "CV",
            PostCodeArea::Crewe => "CW",
            PostCodeArea::Dartford => "DA",
            PostCodeArea::Dundee => "DD",
            PostCodeArea::Derby => "DE",
            PostCodeArea::Dumfries => "DG",
            PostCodeArea::Durham => "DH",
            PostCodeArea::Darlington => "DL",
            PostCodeArea::Doncaster => "DN",
            PostCodeArea::Dorchester => "DT",
            PostCodeArea::Dudley => "DY",
            PostCodeArea::LondonE => "E",
            PostCodeArea::LondonEC => "EC",
            PostCodeArea::Edinburgh => "EH",
            PostCodeArea::Enfield => "EN",
            PostCodeArea::Exeter => "EX",
            PostCodeArea::Falkirk => "FK",
            PostCodeArea::Blackpool => "FY",
            PostCodeArea::Glasgow => "G",
            PostCodeArea::Gloucester => "GL",
            PostCodeArea::Guildford => "GU",
            PostCodeArea::Guernsey => "GY",
            PostCodeArea::Harrow => "HA",
            PostCodeArea::Huddersfield => "HD",
            PostCodeArea::Harrogate => "HG",
            PostCodeArea::HemelHempstead => "HP",
            PostCodeArea::Hereford => "HR",
            PostCodeArea::ComhairleNanEileanSiar => "HS",
            PostCodeArea::Hull => "HU",
            PostCodeArea::Halifax => "HX",
            PostCodeArea::Ilford => "IG",
            PostCodeArea::IsleOfMan => "IM",
            PostCodeArea::Ipswich => "IP",
            PostCodeArea::Inverness => "IV",
            PostCodeArea::Jersey => "JE",
            PostCodeArea::Kilmarnock => "KA",
            PostCodeArea::Kingston => "KT",
            PostCodeArea::Kirkwall => "KW",
            PostCodeArea::Kirkcaldy => "KY",
            PostCodeArea::Liverpool => "L",
            PostCodeArea::Lancaster => "LA",
            PostCodeArea::Llandrindod => "LD",
            PostCodeArea::Leicester => "LE",
            PostCodeArea::Llandudno => "LL",
            PostCodeArea::Lincoln => "LN",
            PostCodeArea::Leeds => "LS",
            PostCodeArea::Luton => "LU",
            PostCodeArea::Manchester => "M",
            PostCodeArea::Medway => "ME",
            PostCodeArea::MiltonKeynes => "MK",
            PostCodeArea::Motherwell => "ML",
            PostCodeArea::LondonN => "N",
            PostCodeArea::Newcastle => "NE",
            PostCodeArea::Nottingham => "NG",
            PostCodeArea::Northampton => "NN",
            PostCodeArea::Newport => "NP",
            PostCodeArea::Norwich => "NR",
            PostCodeArea::LondonNW => "NW",
            PostCodeArea::Oldham => "OL",
            PostCodeArea::Oxford => "OX",
            PostCodeArea::Paisley => "PA",
            PostCodeArea::Peterborough => "PE",
            PostCodeArea::Perth => "PH",
            PostCodeArea::Plymouth => "PL",
            PostCodeArea::Portsmouth => "PO",
            PostCodeArea::Preston => "PR",
            PostCodeArea::AwardingBodies => "QC",
            PostCodeArea::Reading => "RG",
            PostCodeArea::Redhill => "RH",
            PostCodeArea::Romford => "RM",
            PostCodeArea::Sheffield => "S",
            PostCodeArea::Swansea => "SA",
            PostCodeArea::LondonSE => "SE",
            PostCodeArea::Stevenage => "SG",
            PostCodeArea::Stockport => "SK",
            PostCodeArea::Slough => "SL",
            PostCodeArea::Sutton => "SM",
            PostCodeArea::Swindon => "SN",
            PostCodeArea::Southampton => "SO",
            PostCodeArea::Salisbury => "SP",
            PostCodeArea::Sunderland => "SR",
            PostCodeArea::Southend => "SS",
            PostCodeArea::StokeOnTrent => "ST",
            PostCodeArea::LondonSW => "SW",
            PostCodeArea::Shrewsbury => "SY",
            PostCodeArea::Taunton => "TA",
            PostCodeArea::Galashiels => "TD",
            PostCodeArea::Telford => "TF",
            PostCodeArea::Tonbridge => "TN",
            PostCodeArea::Torquay => "TQ",
            PostCodeArea::Truro => "TR",
            PostCodeArea::Cleveland => "TS",
            PostCodeArea::Twickenham => "TW",
            PostCodeArea::Southall => "UB",
            PostCodeArea::LondonW => "W",
            PostCodeArea::Warrington => "WA",
            PostCodeArea::LondonWC => "WC",
            PostCodeArea::Watford => "WD",
            PostCodeArea::Wakefield => "WF",
            PostCodeArea::Wigan => "WN",
            PostCodeArea::Worcester => "WR",
            PostCodeArea::Walsall => "WS",
            PostCodeArea::Wolverhampton => "WV",
            PostCodeArea::York => "YO",
            PostCodeArea::Shetland => "ZE",
        }
    }
}

crate::macros::impl_deserialize!(PostCodeArea);
